### ISSUE TITLE
It's possible to add longitude?

### ISSUE THREAD

**Issue by kweles** [jeancaffou/Analemma#1]
Hi Jeancaffou! 

It's Possible to add longitude to code?

Thanks!

**Comment by jeancaffou** [comment]
Longitude is irrelevant, time is formatted with timezone settings and length of the day depends on how far you are from the Equator (Latitude). Your position relative to some arbitrary line separating West and East doesn't contain any useful information to calculate the time of sunset / sunrise, because timezones do not follow a straight line.
![timezones](https://cloud.githubusercontent.com/assets/922860/10217140/35ace43e-682e-11e5-9f9b-feb32a58ccd5.GIF)

**Comment by kweles** [comment]
Hi Jeancaffou! Thanks for your explanation.
I ask for this, because, i test your class for this data:
- latitude: -23.3393048
- date: 2015-09-30

The result is: 18:03:09

But in PHP with this data:
- latitude: -23.3393048
- longitude: -47.8907999
  
  the result is:  18:10:42

I thought the problem was the longitude.

Thanks!
